{% set name = "sphinx-external-toc" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9c8ea9980ea0e57bf3ce98f6a400f9b69eb1df808f7dd796c9c8cc1873d8b355

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sphinx-etoc = sphinx_external_toc.cli:main

requirements:
  host:
    - pip
    - python >=3.6
#TODO: ##    - python >= 3.7 # v.0.3.0
#TODO: ##    - flit-core >=3.4,<4 # v.0.3.0
  run:
    - attrs >=20.3,<22
    - click >=7.1,<9
    - python >=3.6
    - pyyaml
    - sphinx >=3,<5
test:
  requires:
    - pip
  imports:
    - sphinx_external_toc
  commands:
    - pip check

about:
  home: https://github.com/executablebooks/sphinx-external-toc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A sphinx extension that allows the site-map to be defined in a single YAML file.
  doc_url: https://sphinx-external-toc.readthedocs.io
  dev_url: https://github.com/executablebooks/sphinx-external-toc

extra:
  recipe-maintainers:
    - choldgraf
    - rxm7706
