{% set name = "sphinx-external-toc" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 73198636ada4b4f72f69c7bab09f0e4ce84978056dc5afa9ee51d287bec0a8ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sphinx-etoc = sphinx_external_toc.cli:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs >=20.3,<22
    - click >=7.1,<9
    - python >=3.6
    - pyyaml
    - sphinx >=3,<5
test:
  requires:
    - pip
  imports:
    - sphinx_external_toc
  commands:
    - pip check

about:
  home: https://github.com/executablebooks/sphinx-external-toc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A sphinx extension that allows the site-map to be defined in a single YAML file.
  doc_url: https://sphinx-external-toc.readthedocs.io
  dev_url: https://github.com/executablebooks/sphinx-external-toc

extra:
  recipe-maintainers:
    - choldgraf
